# Generated by Django 5.1.1 on 2024-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesdatesdrf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
