# Generated by Django 5.1.1 on 2024-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesdatesdrf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='previous_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
