# Generated by Django 5.1.1 on 2024-10-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesdatesdrf', '0002_event_previous_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages_left',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
