# Generated by Django 5.1.1 on 2024-10-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesdatesdrf', '0003_user_messages_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='previous_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
