name: Monthly API Call

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  run_monthly_api_call:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Make Monthly API Call
        id: run-monthly-tasks
        run: |
          response=$(curl -X POST "${{ secrets.API_MONTHLY_ENDPOINT }}" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            -w "\n%{http_code}" \
            -s)

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response body: $body"
          echo "Status code: $http_code"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: API call failed with status $http_code"
            echo "Response: $body"
            exit 1
          fi

      - name: Report Failure
        if: ${{ failure() }}
        run: |
          echo "::error::Monthly API job failed. Check the logs for details."
